### ISSUE TITLE
feature request: Disable host key fingerprints check for sshproxy mode

### ISSUE THREAD

**Issue by gaocegege** [ContainerSSH/libcontainerssh#243]
## Please describe what you would like to see in ContainerSSH

```
sshproxy:
  server: localhost
  port: 22222
  username: envd
  privateKey: /home/gaocegege/.config/envd/id_rsa_envd
  allowedHostKeyFingerprints:
   - SHA256:
```

The `allowedHostKeyFingerprints` cannot be empty now. It will be better to add a new config to disable the host key fingerprints check

## Please describe your use case

A clear and concise description of how you would use this feature.
